# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/launch-kit',
                'doc_host': 'https://LotsOfOrg.github.io',
                'git_url': 'https://github.com/LotsOfOrg/launch-kit',
                'lib_path': 'launch_kit'},
  'syms': {'launch_kit.core': {'launch_kit.core.foo': ('core.html#foo', 'launch_kit/core.py')}}}
